### ISSUE TITLE
Doesn't show in the latest Rai Pal 0.11.0

### ISSUE THREAD

**Issue by armax9** [keton/chihuahua#1]
After Rai Pal update, Chihuahua mod no more appear in mod list

**Comment by armax9** [comment]
found the solution, just manually updated the manifest file:
`{
  "title": "Chihuahua",
  "version": "0.1",
  "runnable": {
    "path": "chihuahua.exe",
    "args": [
      "{{ExecutablePath}}",
	  "--uevr-build", "Nightly",
      "--delay", "10"
    ]
  },
  "engine": "Unreal",
  "engineVersionRange": null,
  "unityBackend": null
}`

**Comment by keton** [comment]
this is a bug in Rai Pal. There's already a [commit](https://github.com/Raicuparta/rai-pal/commit/380528098e01d2cbb5bd093f620573e2aa35ce9f) in `main` making `title` optional again.
